pipelines:
    branches:
        main:
            -   step:
                    image: php:8.1-alpine
                    name: 'Install php dependencies'
                    caches:
                        - composer
                    artifacts:
                        - vendor/google/material-symbols/svg/300/outlined/**
                    script:
                        - apk add git
                        - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
                        - COMPOSER_ALLOW_SUPERUSER=1 composer install
            -   step:
#                    image: node:20-alpine
                    image: php:8.1-alpine
                    clone:
                        depth: full
                    name: 'Build & release assets'
                    caches:
                        - node
                    script:
#                        - apk add git
                        - apk add git nodejs npm
                        - npm i && npm rebuild node-sass && npm run prod
                        - echo "Build ${BITBUCKET_BUILD_NUMBER}"
                        - git fetch --all || sleep 3 && git fetch --all
                        - git branch --all
                        - git checkout -b release
                        - git branch -u origin/release
                        - sed '/^\/web\/app\/themes\/saleziani\/assets$/d' .gitignore > .gitignore2 && mv .gitignore2 .gitignore
                        - git add --all
                        - git commit -m "Release ${BITBUCKET_BUILD_NUMBER}"
                        - git push origin release --force
#        release:
#            -   step:
#                    image: php:8.1-alpine
#                    name: 'Install php dependencies'
#                    caches:
#                        - composer
#                    scripts:
#                        - apk add git
