hosts:
    develop:
        stage: develop
        hostname: dw024.nameserver.sk
        port: 20006
        remote_user: ssh-175876
        deploy_path: ~/saleziani.sk/_sub/stage
        branch: release/develop
        php_version: 8.3
    main:
        stage: main
        hostname: dw024.nameserver.sk
        port: 20006
        remote_user: ssh-175876
        deploy_path: ~/saleziani.sk/web
        branch: release/main
        php_version: 8.3
