hosts:
    staging:
        stage: staging
        hostname: dw024.nameserver.sk
        port: 20001
        remote_user: ssh-175876
        deploy_path: ~/saleziani.sk/_sub/stage
        branch: release
#    production:
#        remote_user: deployer
