hosts:
    stage:
        stage: stage
        hostname: dw024.nameserver.sk
        port: 20001
        remote_user: ssh-175876
        deploy_path: ~/saleziani.sk/_sub/stage
        branch: dev-release
        ssh_arguments:
            UserKnownHostsFile: /dev/null
            StrictHostKeyChecking: no
    main:
        stage: main
        hostname: dw024.nameserver.sk
        port: 20001
        remote_user: ssh-175876
        deploy_path: ~/saleziani.sk/web
        branch: main-release
        ssh_arguments:
            UserKnownHostsFile: /dev/null
            StrictHostKeyChecking: no
