hosts:
    stage:
        stage: stage
        hostname: dw024.nameserver.sk
        port: 20006
        remote_user: ssh-175876
        deploy_path: ~/saleziani.sk/_sub/stage
        branch: dev-release
        php_version: 8.3
    main:
        stage: main
        hostname: dw024.nameserver.sk
        port: 20006
        remote_user: ssh-175876
        deploy_path: ~/saleziani.sk/web
        branch: main-release
        php_version: 8.3
