<?php

declare(strict_types=1);

return [
    'campaign' => [
        'labels' => [
            'add_new' => 'Pridať novú',
            'add_new_item' => 'Pridať novú kampaň',
            'all_items' => 'Všetky kampane',
            'archives' => 'Archív kampaní',
            'attributes' => 'Atribúty kampaní',
            'edit_item' => 'Upraviť kampaň',
            'filter_items_list' => 'Filtrovať zoznam kampaní',
            'insert_into_item' => 'Vložiť ku kampani',
            'item_link' => 'Odkaz na kampaň',
            'item_link_description' => 'Odkaz na kampaň.',
            'item_published' => 'Kampaň zverejnená.',
            'item_published_privately' => 'Kampaň zverejnená ako súkromný.',
            'item_reverted_to_draft' => 'Kampaň vrátená do stavu koncept.',
            'item_scheduled' => 'Zverejnenie kampane bolo naplánované.',
            'item_updated' => 'Kampaň aktualizovaná.',
            'items_list' => 'Zoznam kampaní',
            'items_list_navigation' => 'Navigácia v zozname kampaní',
            'name' => 'Kampane',
            'new_item' => 'Nová kampaň',
            'not_found' => 'Kampaň sa nenašla',
            'not_found_in_trash' => 'Kampaň sa v koši nenašla',
            'search_items' => 'Vyhľadať kampaň',
            'singular_name' => 'Kampaň',
            'uploaded_to_this_item' => 'Nahrať ku kampani',
            'view_item' => 'Zobraziť stránku kampane',
            'view_items' => 'Zobraziť kampane',
        ],
        'public' => true,
        'menu_icon' => 'dashicons-megaphone',
        'menu_position' => 20,
        'rewrite' => ['slug' => 'kampane'],
        'show_in_menu' => current_user_can('edit_others_posts'),
        'show_in_rest' => true,
        'supports' => ['title', 'editor', 'thumbnail', 'excerpt'],
    ],
    'newsletter' => [
        'labels' => [
            'add_new' => 'Pridať nový',
            'add_new_item' => 'Pridať nový newsletter',
            'all_items' => 'Všetky newslettre',
            'archives' => 'Archív newsletterov',
            'attributes' => 'Atribúty newsletterov',
            'edit_item' => 'Upraviť newsletter',
            'filter_items_list' => 'Filtrovať zoznam newsletterov',
            'insert_into_item' => 'Vložiť do newslettera',
            'item_link' => 'Odkaz na newsletter',
            'item_link_description' => 'Odkaz na newsletter.',
            'item_published' => 'Newsletter zverejnený.',
            'item_published_privately' => 'Newsletter zverejnený ako súkromný.',
            'item_reverted_to_draft' => 'Newsletter vrátený do stavu koncept.',
            'item_scheduled' => 'Zverejnenie newslettera bolo naplánované.',
            'item_updated' => 'Newsletter aktualizovaný.',
            'items_list' => 'Zoznam newsletterov',
            'items_list_navigation' => 'Navigácia v zozname newsletterov',
            'name' => 'Newslettre',
            'new_item' => 'Nový newsletter',
            'not_found' => 'Newsletter sa nenašiel',
            'not_found_in_trash' => 'Newsletter sa v koši nenašiel',
            'search_items' => 'Vyhľadať newsletter',
            'singular_name' => 'Newsletter',
            'uploaded_to_this_item' => 'Nahrať k newsletteru',
            'view_item' => 'Zobraziť stránku newslettera',
            'view_items' => 'Zobraziť newslettre',
        ],
        'public' => true,
        'menu_icon' => 'dashicons-email',
        'menu_position' => 30,
        'rewrite' => ['slug' => 'newsletter'],
        'show_in_menu' => current_user_can('edit_others_posts'),
        'show_in_rest' => true,
        'supports' => ['title', 'editor'],
    ],
];
