<?php

declare(strict_types=1);

return [
    'call-to-action' => [
        'content' => '<!-- wp:group {"align":"full","backgroundColor":"apricot","className":"wp-pattern-saleziani-call-to-action","layout":{"type":"constrained"}} --><div class="wp-block-group alignfull wp-pattern-saleziani-call-to-action has-apricot-background-color has-background"><!-- wp:group {"layout":{"type":"constrained"}} --><div class="wp-block-group"><!-- wp:heading --><h2 class="wp-block-heading">Vaša podpora je dôležitá</h2><!-- /wp:heading --><!-- wp:paragraph --><p>Saleziánske dielo je sieť saleziánskych komunitných centier, v ktorých tisíce ľudí denne trávia zmysluplný čas. Každý je vítaný. Tvoj pravidelný mesačný príspevok je potrebný pre udržanie a rozvoj športových, kultúrnych, sociálnych a duchovných aktivít pre deti, mladých, rodičov aj seniorov.</p><!-- /wp:paragraph --><!-- wp:buttons --><div class="wp-block-buttons"><!-- wp:button --><div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="#">Podporiť teraz</a></div><!-- /wp:button --></div><!-- /wp:buttons --></div><!-- /wp:group --></div><!-- /wp:group -->',
        'title' => 'Výzva k akcii',
    ],
    'description-link' => [
        'content' => '<!-- wp:wp-bootstrap-blocks/container {"marginAfter":"mb-0"} --><!-- wp:wp-bootstrap-blocks/row {"template":"custom"} --><!-- wp:wp-bootstrap-blocks/column {"sizeMd":8} --><!-- wp:paragraph --><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec rhoncus elit quis nisl vehicula, ac mattis nulla suscipit.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p><a href="#">Dozvedieť sa viac</a></p><!-- /wp:paragraph --><!-- /wp:wp-bootstrap-blocks/column --><!-- /wp:wp-bootstrap-blocks/row --><!-- /wp:wp-bootstrap-blocks/container -->',
        'title' => 'Popis a odkaz',
    ],
    'heading-description-link' => [
        'content' => '<!-- wp:wp-bootstrap-blocks/container {"marginAfter":"mb-0"} --><!-- wp:wp-bootstrap-blocks/row --><!-- wp:wp-bootstrap-blocks/column {"sizeMd":6} --><!-- wp:heading --><h2 class="wp-block-heading">Nadpis</h2><!-- /wp:heading --><!-- /wp:wp-bootstrap-blocks/column --><!-- wp:wp-bootstrap-blocks/column {"sizeMd":6} --><!-- wp:paragraph --><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque orci sem, interdum ac eleifend sed.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p><a href="#">Zobraziť všetko</a></p><!-- /wp:paragraph --><!-- /wp:wp-bootstrap-blocks/column --><!-- /wp:wp-bootstrap-blocks/row --><!-- /wp:wp-bootstrap-blocks/container -->',
        'title' => 'Nadpis, popis a odkaz',
    ],
    'numbers' => [
        'content' => '<!-- wp:heading {"textAlign":"center","textColor":"blackberry"} --><h2 class="wp-block-heading has-text-align-center has-blackberry-color has-text-color">Saleziáni v číslach</h2><!-- /wp:heading --><!-- wp:wp-bootstrap-blocks/container {"marginAfter":"mb-0"} --><!-- wp:wp-bootstrap-blocks/row {"template":"custom"} --><!-- wp:wp-bootstrap-blocks/column {"sizeMd":3,"sizeXs":6} --><!-- wp:paragraph {"align":"center","textColor":"potato","className":"m-0","fontSize":"x-large"} --><p class="has-text-align-center m-0 has-potato-color has-text-color has-x-large-font-size"><strong>200</strong></p><!-- /wp:paragraph --><!-- wp:paragraph {"align":"center","textColor":"potato"} --><p class="has-text-align-center has-potato-color has-text-color"><strong>saleziánov</strong></p><!-- /wp:paragraph --><!-- /wp:wp-bootstrap-blocks/column --><!-- wp:wp-bootstrap-blocks/column {"sizeMd":3,"sizeXs":6} --><!-- wp:paragraph {"align":"center","textColor":"pineapple","className":"m-0","fontSize":"x-large"} --><p class="has-text-align-center m-0 has-pineapple-color has-text-color has-x-large-font-size"><strong>24 165</strong></p><!-- /wp:paragraph --><!-- wp:paragraph {"align":"center","textColor":"pineapple"} --><p class="has-text-align-center has-pineapple-color has-text-color"><strong>detí na táboroch</strong></p><!-- /wp:paragraph --><!-- /wp:wp-bootstrap-blocks/column --><!-- wp:wp-bootstrap-blocks/column {"sizeMd":3,"sizeXs":6} --><!-- wp:paragraph {"align":"center","textColor":"lime","className":"m-0","fontSize":"x-large"} --><p class="has-text-align-center m-0 has-lime-color has-text-color has-x-large-font-size"><strong>1 050</strong></p><!-- /wp:paragraph --><!-- wp:paragraph {"align":"center","textColor":"lime"} --><p class="has-text-align-center has-lime-color has-text-color"><strong>podujatí</strong></p><!-- /wp:paragraph --><!-- /wp:wp-bootstrap-blocks/column --><!-- wp:wp-bootstrap-blocks/column {"sizeMd":3,"sizeXs":6} --><!-- wp:paragraph {"align":"center","textColor":"blueberry","className":"m-0","fontSize":"x-large"} --><p class="has-text-align-center m-0 has-blueberry-color has-text-color has-x-large-font-size"><strong>17</strong></p><!-- /wp:paragraph --><!-- wp:paragraph {"align":"center","textColor":"blueberry"} --><p class="has-text-align-center has-blueberry-color has-text-color"><strong>projektov</strong></p><!-- /wp:paragraph --><!-- /wp:wp-bootstrap-blocks/column --><!-- /wp:wp-bootstrap-blocks/row --><!-- /wp:wp-bootstrap-blocks/container -->',
        'title' => 'Čísla',
    ],
    'three-links-to-pages' => [
        'content' => '<!-- wp:wp-bootstrap-blocks/container {"marginAfter":"mb-0"} --><!-- wp:wp-bootstrap-blocks/row {"template":"custom"} --><!-- wp:wp-bootstrap-blocks/column {"sizeMd":4,"sizeSm":6} --><!-- wp:saleziani/link-to-page /--><!-- /wp:wp-bootstrap-blocks/column --><!-- wp:wp-bootstrap-blocks/column {"sizeMd":4,"sizeSm":6} --><!-- wp:saleziani/link-to-page /--><!-- /wp:wp-bootstrap-blocks/column --><!-- wp:wp-bootstrap-blocks/column {"sizeMd":4,"sizeSm":6} --><!-- wp:saleziani/link-to-page /--><!-- /wp:wp-bootstrap-blocks/column --><!-- /wp:wp-bootstrap-blocks/row --><!-- /wp:wp-bootstrap-blocks/container -->',
        'title' => '3 x odkaz na stránku',
    ],
];
